### ISSUE TITLE
Biguery: response too large

### ISSUE THREAD

**Issue by gpopovic** [GoogleCloudPlatform/DataflowPythonSDK#18]
I'm getting this error when using bigquery as input

`{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "responseTooLarge",
    "message": "Response too large to return. Consider setting allowLargeResults to true in your job configuration. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors"
   }
  ],
  "code": 403,
  "message": "Response too large to return. Consider setting allowLargeResults to true in your job configuration. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors"
 }
`

p = df.Pipeline(argv=['--project', project])
p | df.Read('read', df.io.BigQuerySource(input_table)

I know that i have to set allowLargeResults to true, but i cant seem to be able to find that option.

**Comment by chamikaramj** [comment]
I believe this is happening since you are using DirectPipelineRunner. 

DirectlyPipelineRunner is currently designed for testing your pipeline using small datasets. For larger datasets, currently you have to use a distributed runner implementation such as DataflowPipelineRunner.

To use DataflowPipelineRunner, please sign up for using Python Cloud Dataflow Alpha here: https://github.com/GoogleCloudPlatform/DataflowPythonSDK/blob/master/README.md#signing-up-for-alpha-batch-cloud-execution

Please let us know if you run into any further issues.

**Comment by jerjou** [comment]
I ran into this too, when using the bigquery api directly (through the python client sdk).
If the bigquery source is the entire table (as opposed to a query on a table), the dataflow sdk can actually get around this problem by issuing a [tabledata.list](https://cloud.google.com/bigquery/docs/reference/v2/tabledata/list) request, instead of doing a query for * like it's currently doing.

**Comment by chamikaramj** [comment]
Ack. We'll look into updating BigQuery source so that it can produce larger datasets when used with DirectPipelineRunner. We are also looking into improving performance of DirectPipelineRunner so that it can handle larger datasets. I do not have exact timelines for these for now though.

**Comment by gpopovic** [comment]
I am whitelisted and I can confirm that this works when deploying to gce.

I tried before and it didn't work...i suppose i screwed something back then.

**Comment by pbhatia243** [comment]
I am facing the same issue. Could you elaborate , what configuration changes you made to make it work ?

**Comment by jerjou** [comment]
I believe the "easy" way to fix it is to run the pipeline using the Cloud Dataflow service, instead of locally, since the service won't use the DirectPipelineRunner, which is meant more for testing smaller datasets that shouldn't have this issue :)

The more complex fix that I proposed was to modify the [BigQueryReader](https://github.com/apache/incubator-beam/blob/python-sdk/sdks/python/apache_beam/io/bigquery.py#L450) to [list the table](https://developers.google.com/resources/api-libraries/documentation/bigquery/v2/python/latest/bigquery_v2.tabledata.html#list) instead of a querying it, in the case where you just want the whole table.

**Comment by gpopovic** [comment]
@pbhatia243  @jerjou  is correct...you have to run it on Dataflow service if you want it to work that way
