### ISSUE TITLE
Fix the dependency on oauth2client locked to 1.5.2

### ISSUE THREAD

**Issue by gramster** [GoogleCloudPlatform/DataflowPythonSDK#7]
This is causing lots of issues with other packages like gcloud Python SDK which requires > 2.0

**Comment by silviulica** [comment]
Ack. Coming in the next release.

**Comment by silviulica** [comment]
Ummm, I was too rush. It turns out that google-apitools pinned at 0.4.11 does not work with oauth2client latest (>=2.0.0). If we unpin google-apitools then the Apiary client libraries built using it (dataflow, bigquery, and storage) will break. So we need new versions of those. Basically we need some careful sequencing here. I will ping the issue when we make progress.

**Comment by silviulica** [comment]
This should be fixed in v0.2.3 just released.
